"""Type stubs for transformers library."""

from typing import Any

__version__: str

class Tokenizer:
    """Tokenizer class."""
    eos_token_id: int
    def decode(self, *args: Any, **kwargs: Any) -> str: ...

class AutoProcessor:
    """Auto processor class for transformers."""
    tokenizer: Tokenizer
    @classmethod
    def from_pretrained(cls, model_name_or_path: str, **kwargs: Any) -> "AutoProcessor": ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_chat_template(self, *args: Any, **kwargs: Any) -> Any: ...
    def batch_decode(self, *args: Any, **kwargs: Any) -> list[str]: ...

class AutoModelForImageTextToText:
    """Auto model for image-to-text tasks."""
    @classmethod
    def from_pretrained(cls, model_name_or_path: str, **kwargs: Any) -> "AutoModelForImageTextToText": ...
    def to(self, device: str) -> "AutoModelForImageTextToText": ...
    def eval(self) -> "AutoModelForImageTextToText": ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def generate(self, *args: Any, **kwargs: Any) -> Any: ...
