"""Type stubs for ultralytics."""

from typing import Any

class YOLO:
    """YOLO model class."""
    def __init__(self, model: str) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def predict(self, *args: Any, **kwargs: Any) -> Any: ...
    def to(self, device: str) -> "YOLO": ...
